server {
  server_name innafaithtattoo.hu www.innafaithtattoo.hu;
  root /var/www/fanni_idopontfoglalo_prod_test/frontend/build;
  index index.html index.htm;

  location / {
    try_files $uri /index.html;
  }

  # Django’s new static location
  location /django-static/ {
    alias /var/www/fanni_idopontfoglalo_prod_test/static/;
  }

  location /media/ {
    alias /var/www/fanni_idopontfoglalo_prod_test/media/;
  }

  location /api/ {
    proxy_pass http://unix:/var/www/fanni_idopontfoglalo_prod_test/gunicorn.sock;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/innafaithtattoo.hu/fullchain.pem; # managed by Certbot  
    ssl_certificate_key /etc/letsencrypt/live/innafaithtattoo.hu/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot


}

server {
    if ($host = www.innafaithtattoo.hu) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    if ($host = innafaithtattoo.hu) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


  listen 80;
  server_name innafaithtattoo.hu www.innafaithtattoo.hu;
    return 404; # managed by Certbot
}